import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {validEvent,acquisitionChannel} from '../dist/analytics-schema.mjs';
import {createMeasurement} from '../dist/analytics-client.mjs';
import {recordEvent,measurementHandler,expireAggregates} from '../server/measurement.mjs';
const event=(extra={})=>({v:1,id:randomUUID(),event:'page_view',kind:'none',channel:'direct',category:'none',failure:'none',...extra});
const pause=()=>new Promise(r=>setTimeout(r,0));
function memoryStore(){let data=null,version=0;return {getWithMetadata:async()=>data?{data:structuredClone(data),etag:String(version)}:null,setJSON:async(k,next,options)=>{if((options.onlyIfNew&&data)||(options.onlyIfMatch&&options.onlyIfMatch!==String(version)))return {modified:false};data=structuredClone(next);version++;return {modified:true};},read:()=>data};}
test('measurement allowlist rejects address, coordinates, free text, URL and invalid IDs',()=>{assert.ok(validEvent(event()));for(const x of [{address:'test'},{lat:1},{channel:'https://example.com/private'},{category:'custom text'},{id:'not-random'}])assert.equal(validEvent(event(x)),false);});
test('acquisition extracts fixed labels only and never serializes private URL parts',()=>{assert.equal(acquisitionChannel('https://example.com/?utm_source=github&address=secret'),'github');assert.equal(acquisitionChannel('https://example.com/?utm_source=secret'),'other');assert.equal(acquisitionChannel('https://example.com/#sb=anything'),'shared');assert.equal(acquisitionChannel('https://example.com/','https://github.com/private?secret=1'),'github');assert.equal(acquisitionChannel('https://example.com/','https://unknown.example/private'),'other');});
test('aggregate store counts concurrent unique events once and repeated deliveries once',async()=>{const s=memoryStore(),e=event();await Promise.all([recordEvent(s,e),recordEvent(s,e),recordEvent(s,event())]);assert.equal(s.read().events,2);assert.equal(Object.values(s.read().counts).reduce((a,b)=>a+b,0),2);assert.equal(await recordEvent(s,e),'duplicate');assert.equal(s.read().events,2);assert.deepEqual(Object.keys(s.read()).sort(),['counts','day','events','ids','schema']);});
test('contention and per-day capacity fail closed with bounded writes',async()=>{let writes=0;const s={getWithMetadata:async()=>null,setJSON:async()=>{writes++;return {modified:false};}};assert.equal(await recordEvent(s,event()),'busy');assert.equal(writes,5);assert.equal(await recordEvent({getWithMetadata:async()=>({data:{ids:[],events:10000}})},event()),'full');});
test('HTTP collector requires origin, method, type, bounded body and exact schema',async()=>{const s=memoryStore(),handler=measurementHandler(()=>s),url='https://example.com/api/measure';const req=(body,extra={})=>new Request(url,{method:'POST',headers:{origin:'https://example.com','content-type':'application/json',...extra},body:JSON.stringify(body)});assert.equal((await handler(new Request(url))).status,405);assert.equal((await handler(req(event(),{origin:'https://other.example'}))).status,403);assert.equal((await handler(req(event(),{'content-type':'text/plain'}))).status,415);assert.equal((await handler(req({x:'a'.repeat(2000)}))).status,413);assert.equal((await handler(req(event({address:'test'})))).status,400);const e=event();assert.equal((await (await handler(req(e))).json()).code,'recorded');assert.equal((await (await handler(req(e))).json()).code,'duplicate');assert.equal(s.read().events,1);assert.equal((await measurementHandler(()=>{throw Error('private detail');})(req(event()))).status,503);});
test('retention removes only own expired day keys, preserving current and unrelated entries',async()=>{const deleted=[],store={async *list(){yield {blobs:['daily/2026-09-06.json','daily/2026-09-07.json','daily/2026-10-07.json','unrelated/2020-01-01.json','daily/invalid.json'].map(key=>({key}))};},delete:async k=>deleted.push(k)};await expireAggregates(store,Date.parse('2026-10-07T12:00:00Z'));assert.deepEqual(deleted,['daily/2026-09-06.json','daily/2026-09-07.json']);});
test('client opt-in, no duplicate pageview, opt-out and failed transport are isolated',async()=>{const sent=[],states=[];const c=createMeasurement({uuid:randomUUID,channel:'qa',send:async e=>{sent.push(e);return true;},onState:s=>states.push(s)});assert.equal(c.event('share_clicked'),false);c.setEnabled(true);await pause();c.setEnabled(false);c.setEnabled(true);await pause();assert.equal(sent.length,1);c.event('analysis_succeeded',{kind:'public',address:'not forwarded'});await pause();assert.equal(sent.length,2);assert.equal('address' in sent[1],false);c.setEnabled(false);assert.equal(c.event('analysis_started'),false);const failed=createMeasurement({uuid:randomUUID,channel:'direct',send:async()=>{throw Error('offline');},onState:s=>states.push(s)});failed.setEnabled(true);await pause();assert.ok(states.includes('unavailable'));failed.setEnabled(false);});
test('client consent revocation aborts pending requests without durable queue',async()=>{let observed;const c=createMeasurement({uuid:randomUUID,channel:'direct',send:async(e,signal)=>{observed=signal;return new Promise(resolve=>signal.addEventListener('abort',()=>resolve(false),{once:true}));}});c.setEnabled(true);await pause();c.setEnabled(false);assert.equal(observed.aborted,true);});
