import test from 'node:test';import assert from 'node:assert/strict';
import {validateRelease,coveringTiles,readBounded,boundedDecompress,createTileTransport,normalizeTileFeature} from '../dist/overture.mjs';
const now=Date.parse('2026-10-06T12:00:00Z'),origin={lat:0,lon:0};
const feature=(properties={})=>({type:'Feature',geometry:{type:'Point',coordinates:[0,0]},properties:{id:'00000000-0000-4000-8000-000000000001',taxonomy:JSON.stringify({primary:'grocery_store',hierarchy:['shopping','grocery_store']}),operating_status:'open',...properties}});
test('release discovery is strict, dated and refuses stale/future inputs',()=>{assert.equal(validateRelease({latest:'2026-09-23.1'},now).sourceTime,'2026-09-23T00:00:00Z');for(const latest of ['2026-02-30.1','2026-08-01.0','2026-11-01.0','../../secret','2026-09-23',null])assert.throws(()=>validateRelease({latest},now));});
test('spherical bounding tiles cover independently generated circle destinations and the dateline',()=>{
 for(const p of [origin,{lat:37.77929,lon:-122.41926},{lat:71.3,lon:-156.8},{lat:0,lon:179.999}])for(const z of [13,14]){
  const tiles=new Set(coveringTiles(p,z).map(t=>`${t.x}/${t.y}`)),rad=Math.PI/180;
  for(let angle=0;angle<360;angle+=5){const a=angle*rad,d=600/6371008.8,lat=Math.asin(Math.sin(p.lat*rad)*Math.cos(d)+Math.cos(p.lat*rad)*Math.sin(d)*Math.cos(a)),lon=p.lon*rad+Math.atan2(Math.sin(a)*Math.sin(d)*Math.cos(p.lat*rad),Math.cos(d)-Math.sin(p.lat*rad)*Math.sin(lat));const n=2**z,x=((Math.floor((lon/rad+180)/360*n)%n)+n)%n,y=Math.floor((1-Math.asinh(Math.tan(lat))/Math.PI)/2*n);assert.ok(tiles.has(`${x}/${y}`));}
 }assert.throws(()=>coveringTiles({lat:89,lon:0},14));
});
test('normalization discards identifying and confidence fields, preserves only broad categories',()=>{const r=normalizeTileFeature(feature({names:'sensitive-looking provider text',phones:'123',confidence:0.01}),'place',origin);assert.deepEqual(r,{id:'overture/00000000-0000-4000-8000-000000000001',lon:0,lat:0,retail:'food',service:null,transit:false});assert.equal(normalizeTileFeature(feature({operating_status:'permanently_closed'}),'place',origin),null);});
test('unknown categories remain absent, malformed taxonomy and ids rejected',()=>{assert.equal(normalizeTileFeature(feature({taxonomy:undefined}),'place',origin),null);assert.equal(normalizeTileFeature(feature({taxonomy:JSON.stringify({primary:'unrecognized',hierarchy:['unrecognized']})}),'place',origin),null);for(const p of [{id:'bad'},{taxonomy:'{'},{taxonomy:JSON.stringify({primary:'bank',hierarchy:['shopping']})}])assert.throws(()=>normalizeTileFeature(feature(p),'place',origin));});
test('only qualified public point infrastructure is used; clipped polygons never become invented points',()=>{const f=feature({subtype:'transit',class:'bus_stop',source_tags:'{}'});assert.equal(normalizeTileFeature(f,'infrastructure',origin).transit,true);assert.equal(normalizeTileFeature({...f,geometry:{type:'Polygon',coordinates:[]}},'infrastructure',origin),null);assert.equal(normalizeTileFeature(feature({subtype:'transit',class:'bus_stop',source_tags:'{"access":"private"}'}),'infrastructure',origin),null);assert.equal(normalizeTileFeature(feature({subtype:'transit',class:'bicycle_rental'}),'infrastructure',origin),null);});
test('bounded streams reject inflated data and unsupported decompression',async()=>{await assert.rejects(readBounded(new Blob(['a'.repeat(11)]).stream(),10),/limit/);assert.equal((await readBounded(new Blob(['hello']).stream(),10)).byteLength,5);await assert.rejects(boundedDecompress(new ArrayBuffer(0),4),/compression/);});
function rangeResponse(start=0,end=2,etag='fixed',body='abc'){return new Response(body,{status:206,headers:{'content-range':`bytes ${start}-${end}/1000`,etag}});}
test('range transport verifies status, exact range, byte count and immutable ETags',async()=>{const source=createTileTransport({fetchImpl:async()=>rangeResponse()}).source('https://example.invalid');assert.equal((await source.getBytes(0,3)).data.byteLength,3);for(const r of [new Response('abc'),rangeResponse(1,3),rangeResponse(0,2,'fixed','a')])await assert.rejects(createTileTransport({fetchImpl:async()=>r}).source('https://example.invalid').getBytes(0,3),/range/);await assert.rejects(source.getBytes(0,3,null,'other'),/changed/);await assert.rejects(source.getBytes(-1,3),/range/);});
test('transient failures retry once with a shared budget; 429 never retries',async()=>{let calls=0,sleeps=0;const transport=createTileTransport({fetchImpl:async()=>++calls===1?new Response('',{status:503}):rangeResponse(),sleep:async()=>{sleeps++;}});await transport.source('https://example.invalid').getBytes(0,3);assert.equal(calls,2);assert.equal(sleeps,1);assert.equal(transport.stats().retries,1);calls=0;await assert.rejects(createTileTransport({fetchImpl:async()=>{calls++;return new Response('',{status:429,headers:{'retry-after':'120'}});}}).request('https://example.invalid'),e=>e.retryAfterMs===120000);assert.equal(calls,1);});
test('cancellation does not issue another network call',async()=>{const c=new AbortController();c.abort();let calls=0;await assert.rejects(createTileTransport({signal:c.signal,fetchImpl:async()=>{calls++;return rangeResponse();}}).request('https://example.invalid'),/cancelled/);assert.equal(calls,0);});
test('gzip inflation is bounded even when compressed size is tiny',async()=>{
 const source=new Blob([new Uint8Array(33*1024*1024)]).stream().pipeThrough(new CompressionStream('gzip'));
 const compressed=await new Response(source).arrayBuffer();assert.ok(compressed.byteLength<100000);
 await assert.rejects(boundedDecompress(compressed,2),/safety limit/);
});
test('retail, service and station mappings do not add new scoring dimensions',()=>{
 for(const [primary,group] of [['bank','banking'],['pharmacy','pharmacy'],['post_office','postal'],['library','library'],['public_restroom','toilets']])assert.equal(normalizeTileFeature(feature({taxonomy:JSON.stringify({primary,hierarchy:[primary]})}),'place',origin).service,group);
 for(const primary of ['bus_station','train_station','subway_station','tram_station'])assert.equal(normalizeTileFeature(feature({taxonomy:JSON.stringify({primary,hierarchy:[primary]})}),'place',origin).transit,true);
 const nested=feature({taxonomy:JSON.stringify({primary:'fictional_specialized_grocery',hierarchy:['shopping','grocery_store','fictional_specialized_grocery']})});assert.equal(normalizeTileFeature(nested,'place',origin).retail,'food');
});
test('stale release and failed partial archive never return a context',async()=>{
 const {retrieveOverture}=await import('../dist/overture.mjs');
 await assert.rejects(retrieveOverture(origin,{now,fetchImpl:async()=>new Response(JSON.stringify({latest:'2025-01-01.0'}))}),/stale/);
 let calls=0;await assert.rejects(retrieveOverture(origin,{now,fetchImpl:async()=>++calls===1?new Response(JSON.stringify({latest:'2026-09-23.1'})):new Response('unavailable',{status:404})}),/unavailable/);assert.equal(calls,2);
});
