import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {csvCell,exportSubmissions,exportAnalytics} from '../server/owner-export.mjs';import {ownerExport} from '../scripts/owner-export.mjs';
const now=Date.parse('2026-10-07T12:00:00Z');const store=rows=>({async *list(){yield {blobs:rows.map((_,i)=>({key:String(i)}))};},get:async k=>rows[Number(k)]});
const r={v:1,id:randomUUID(),type:'interest',kind:'public',website:'',role:'operator',interests:['competition'],email:'+qa@example.com',contactConsent:true,receivedAt:new Date(now).toISOString()};
test('CSV cells prevent formula execution after leading whitespace and quote commas/newlines',()=>{for(const value of ['=1+1','+1','-1','@sum(A1)',' \t=1','\n=1'])assert.ok(csvCell(value).startsWith('"\''));assert.equal(csvCell('a,"b"'),'"a,""b"""');});
test('contact export excludes expired/QA and unknown fields; protects email formula prefixes',async()=>{const csv=await exportSubmissions(store([r,{...r,kind:'synthetic'},{...r,receivedAt:'2026-01-01T00:00:00Z'},{...r,address:'private'}]),'interest',{now});assert.equal(csv.split('\r\n').length,3);assert.match(csv,/'\+qa@example.com/);assert.doesNotMatch(csv,/private|synthetic/);});
test('analytics export allows only bounded schema and excludes QA/synthetic and old dates',async()=>{const counts={'page_view|none|direct|none|none':3,'page_view|none|qa|none|none':9,'analysis_succeeded|synthetic|direct|none|none':2,'untrusted|none|direct|none|none':5};const csv=await exportAnalytics(store([{day:'2026-10-07',counts},{day:'2026-01-01',counts}]),{now});assert.match(csv,/"3"/);assert.doesNotMatch(csv,/"9"|untrusted|2026-01/);});
test('unauthorized export stops before accessing storage or disk',async()=>{await assert.rejects(ownerExport({env:{},args:['--out','/tmp/not-created'],storeFactory:()=>assert.fail()}),/authorization_required/);});
test('repository output is forbidden before touching stores',async()=>{await assert.rejects(ownerExport({env:{NETLIFY_AUTH_TOKEN:'mock',SITEBUDDY_SITE_ID:'mock'},args:['--out',process.cwd()],storeFactory:()=>assert.fail()}),/output_inside_repository/);});
