import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {mailConfig,queueLead,queueDigest,summarize,processJob,runMail,resendSend} from '../server/owner-mail.mjs';
import {submissionHandler} from '../server/submissions.mjs';
const now=Date.parse('2026-10-07T12:00:00Z'),config={to:'owner@example.com',from:'sender@example.com',key:'mock-only',since:now-86400000};
const record=(extra={})=>({v:1,id:randomUUID(),type:'interest',kind:'public',website:'',role:'operator',interests:['competition'],email:'synthetic@example.com',contactConsent:true,receivedAt:new Date(now).toISOString(),...extra});
function store(){let v=0;const rows=new Map();return {rows,get:async k=>structuredClone(rows.get(k)?.data??null),getWithMetadata:async k=>structuredClone(rows.get(k)??null),setJSON:async(k,data,o={})=>{const old=rows.get(k);if(o.onlyIfNew&&old||o.onlyIfMatch&&old?.etag!==o.onlyIfMatch)return {modified:false};rows.set(k,{data:structuredClone(data),etag:String(++v)});return {modified:true};},delete:async k=>rows.delete(k),async *list({prefix=''}){yield {blobs:[...rows.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))};}};}
async function queued(extra={}){const s=store(),r=record(extra);await s.setJSON(`interest/${r.id}.json`,r);await queueLead(s,r,now);return {s,r,k:`mail/lead-${r.id}.json`};}
test('mail stays disabled without explicit production authorization and rejects injected configuration',()=>{assert.equal(mailConfig({},'production'),null);assert.equal(mailConfig({SITEBUDDY_MAIL_ENABLED:'1'},'deploy-preview'),null);assert.throws(()=>mailConfig({SITEBUDDY_MAIL_ENABLED:'1',SITEBUDDY_OWNER_EMAIL:'a@example.com\nb@example.com'},'production'));});
test('only opted-in public leads create an idempotent durable outbox record',async()=>{const s=store();for(const extra of [{kind:'synthetic'},{email:'',contactConsent:false},{contactConsent:false},{email:'bad\n@example.com'}])assert.equal(await queueLead(s,record(extra),now),false);const r=record();assert.equal(await queueLead(s,r,now),true);assert.equal(await queueLead(s,r,now),false);assert.equal(s.rows.size,1);assert.equal(JSON.stringify([...s.rows.values()]).includes(r.email),false);});
test('concurrent worker sends once, retries use same key and immutable payload, accepted never resends',async()=>{const {s,k}=await queued();const sent=[];const send=async(p,o)=>{sent.push([p,o.idempotencyKey]);return {ok:true,providerId:'mock-message'};};await Promise.all([processJob(s,k,config,{now,send}),processJob(s,k,config,{now,send})]);await processJob(s,k,config,{now:now+120000,send});assert.equal(sent.length,1);assert.deepEqual(sent[0][0].to,['owner@example.com']);assert.equal((await s.get(k)).state,'accepted');assert.doesNotMatch(JSON.stringify(sent),/address|coordinate|analytics|reply_to|html/i);});
test('temporary outage preserves source, backs off and safely recovers',async()=>{const {s,k,r}=await queued();let calls=0;const keys=[];const send=async(p,o)=>{keys.push(o.idempotencyKey);return ++calls===1?{ok:false,retryable:true,code:'provider_unavailable'}:{ok:true,providerId:'mock-message'};};assert.equal(await processJob(s,k,config,{now,send}),'retry');await processJob(s,k,config,{now:now+100,send});assert.equal(calls,1);assert.equal(await processJob(s,k,config,{now:now+60001,send}),'accepted');assert.equal(new Set(keys).size,1);assert.ok(await s.get(`interest/${r.id}.json`));});
test('ambiguous sends never retry beyond the provider idempotency safety window',async()=>{const {s,k}=await queued();let calls=0;const send=async()=>{calls++;throw Error('private provider URL');};await processJob(s,k,config,{now,send});assert.equal(await processJob(s,k,config,{now:now+23*3600000,send}),'ambiguous_window_expired');assert.equal(calls,1);assert.doesNotMatch(JSON.stringify(await s.get(k)),/private provider URL/);});
test('payload/configuration change after an ambiguous attempt stops rather than duplicating',async()=>{const {s,k}=await queued();await processJob(s,k,config,{now,send:async()=>({ok:false,retryable:true,code:'timeout'})});assert.equal(await processJob(s,k,{...config,from:'new@example.com'},{now:now+60001,send:async()=>assert.fail()}),'configuration_or_content_changed');});
test('digest excludes QA and never includes email, suppresses empty periods and deduplicates',async()=>{const day='2026-10-07',s=store(),sum=summarize([record(),record({kind:'synthetic'}),record({email:'',contactConsent:false})],day);assert.equal(sum.interest,2);assert.equal(sum.contacts,1);assert.doesNotMatch(JSON.stringify(sum),/@/);assert.equal(await queueDigest(s,summarize([],day),now),false);assert.equal(await queueDigest(s,sum,now),true);assert.equal(await queueDigest(s,sum,now),false);});
test('outbox failure does not change durable form acknowledgement',async()=>{const s=store(),r=record();delete r.receivedAt;const h=submissionHandler(()=>s,{onStored:()=>{throw Error('queue unavailable');}});const response=await h(new Request('https://example.com/api/interest',{method:'POST',headers:{origin:'https://example.com','content-type':'application/json'},body:JSON.stringify(r)}));assert.equal(response.status,200);assert.ok(await s.get(`interest/${r.id}.json`));});
test('recovery discovers missed queue writes, excludes records predating authorization and QA',async()=>{const s=store(),a=record(),b=record({receivedAt:new Date(config.since-1).toISOString()}),c=record({kind:'synthetic'});for(const r of [a,b,c])await s.setJSON(`interest/${r.id}.json`,r);let calls=0;await runMail(s,config,{now,send:async()=>{calls++;return {ok:true,providerId:'mock-message'};}});assert.equal(calls,1);assert.equal((await s.get(`mail/lead-${a.id}.json`)).state,'accepted');assert.equal(await s.get(`mail/lead-${b.id}.json`),null);assert.equal(await s.get(`mail/lead-${c.id}.json`),null);});
test('provider timeout, 429/500 retry, 403 permanent and malformed acknowledgement stay sanitized',async()=>{for(const status of [429,500,403]){const result=await resendSend({}, {key:'mock',idempotencyKey:'mock',fetchImpl:async()=>new Response('secret',{status})});assert.equal(result.retryable,status!==403);assert.doesNotMatch(JSON.stringify(result),/secret/);}const result=await resendSend({}, {key:'mock',idempotencyKey:'mock',timeoutMs:5,fetchImpl:(_,o)=>new Promise((_,reject)=>o.signal.addEventListener('abort',()=>reject(Error('private'))))});assert.equal(result.code,'timeout_or_network');});
test('daily hard reservation ceiling prevents provider calls even with a valid job',async()=>{const {s,k}=await queued();await s.setJSON('mail-control/budget.json',{day:'2026-10-07',month:'2026-10',daily:90,monthly:90,nextAt:0});assert.equal(await processJob(s,k,config,{now,send:async()=>assert.fail()}),'quota');assert.equal((await s.get(k)).attempts,0);});
test('six failures are terminal; expired source cannot be recreated as a notification',async()=>{const {s,k,r}=await queued();let time=now,calls=0;const send=async()=>{calls++;return {ok:false,retryable:true,code:'unavailable'};};for(let i=0;i<6;i++){await processJob(s,k,config,{now:time,send});time+=3600001;}assert.equal(await processJob(s,k,config,{now:time,send}),'attempts_exhausted');assert.equal(calls,6);const other=await queued();await other.s.delete(`interest/${other.r.id}.json`);assert.equal(await processJob(other.s,other.k,config,{now,send:async()=>assert.fail()}),'source_unavailable');});
test('mail retention works while sending is disabled and operational counters contain no identity',async()=>{const {expireMail,recordHealth}=await import('../server/owner-mail.mjs');const s=store();await s.setJSON('mail/old.json',{createdAt:now-92*86400000,state:'accepted'});await s.setJSON('mail/recent.json',{createdAt:now,state:'accepted'});await s.setJSON('ops/2026-01-01.json',{persistence_failed:1});await Promise.all([recordHealth(s,'persistence_failed',now),recordHealth(s,'persistence_failed',now)]);assert.equal((await s.get('ops/2026-10-07.json')).persistence_failed,2);assert.equal(await expireMail(s,now),2);assert.ok(await s.get('mail/recent.json'));});
test('oversized and missing provider identifiers remain ambiguous rather than accepted',async()=>{for(const body of [JSON.stringify({wrong:'field'}),'x'.repeat(5000)]){const result=await resendSend({}, {key:'mock',idempotencyKey:'mock',fetchImpl:async()=>new Response(body)});assert.equal(result.ok,false);assert.equal(result.retryable,true);}});
test('digest waits until 00:05 UTC for in-flight prior-day persistence',async()=>{const s=store(),midnight=Date.parse('2026-10-08T00:00:00Z');await s.setJSON(`interest/${randomUUID()}.json`,record({email:'',contactConsent:false}));await runMail(s,config,{now:midnight,send:async()=>assert.fail()});assert.equal(await s.get('mail/digest-2026-10-07.json'),null);await runMail(s,config,{now:midnight+300000,send:async()=>({ok:true,providerId:'mock-digest'})});assert.equal((await s.get('mail/digest-2026-10-07.json')).state,'accepted');});
