import test from 'node:test';import assert from 'node:assert/strict';
import {assess,MODEL_VERSION} from '../dist/model.mjs';import {sample} from '../dist/samples.mjs';
import {createSummary,shareURL,readShared,validateShared,summaryText,deliverShare} from '../dist/share.mjs';
function snapshot(kind='mixed'){const s=sample(kind);return {...s,kind:'synthetic',modelVersion:MODEL_VERSION,fetchedAt:s.evaluationTime,assessment:assess(s.raw,s.origin,{now:Date.parse(s.evaluationTime)}),label:'confidential-placeholder',email:'never-share@example.invalid'};}
test('shared summary roundtrips without address, records, identifiers or search query',()=>{const input=snapshot();const url=shareURL(input,'https://sitebuddy.example/path?address=private#old');assert.equal(new URL(url).search,'');assert.equal(new URL(url).pathname,'/');const result=readShared(new URL(url).hash);assert.equal(result.total,7.5);assert.deepEqual(result,createSummary(input));for(const banned of ['confidential','email','origin','records','lat','lon','private'])assert.ok(!decodeURIComponent(url).includes(banned));assert.match(summaryText(result),/fictional example/);});
test('sparse shared data remains unknown; no invented total',()=>{const s=createSummary(snapshot('sparse'));assert.equal(s.total,null);assert.equal(s.scores.filter(x=>x===null).length,2);assert.match(summaryText(s),/not enough/);});
test('malformed, oversized, extra fields and inconsistent summaries are rejected',()=>{const s=createSummary(snapshot());for(const v of [{...s,total:10},{...s,address:'hidden'},{...s,scores:[1,2]},{...s,scores:[NaN,2,3]},{...s,day:'2026-02-30'},{...s,model:'private'},{...s,kind:'verified'}])assert.throws(()=>validateShared(v));for(const hash of ['#sb=%zz','#sb='+ 'x'.repeat(1600),'#sb=null'])assert.throws(()=>readShared(hash));assert.equal(readShared('#method'),null);assert.throws(()=>shareURL(snapshot(),'javascript:alert(1)'));});
test('sharing preserves exact original mean rather than averaging rounded display values',()=>{const s=snapshot();s.assessment.dimensions[2].score=8.56;s.assessment.score=7.5;assert.equal(createSummary(s).total,7.5);});
test('clipboard success, denial, unsupported API and stalled attempt remain recoverable',async()=>{let calls=0;assert.equal(await deliverShare({text:'t',url:'u',writeText:async text=>{calls++;assert.equal(text,'t\nu');}}),'copied');assert.equal(calls,1);assert.equal(await deliverShare({writeText:async()=>{throw Error('denied');}}),'manual');assert.equal(await deliverShare({}),'manual');assert.equal(await deliverShare({writeText:()=>new Promise(()=>{}),timeoutMs:10}),'manual');});
